name: CI Pipeline

# Trigger the pipeline on push or pull requests to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define jobs in the pipeline
jobs:
  build-and-test:
    # The virtual environment to run the job on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run test
        run: npm test
